### ISSUE TITLE
Following a link.

### ISSUE THREAD

**Issue by Mandulai** [nobodyinperson/thunar-custom-actions#15]
Hello! Couldn't find this feature anywhere. I see you understand this!
How to make in the context menu on RMB ... the ability to navigate to the folder that contains the original file? Something like "Go to destination.." in Nemo. Or poke please where it is painted. Thanks in advance!!!

**Comment by nobodyinperson** [comment]
I don't think this is possible unfortunately. Maybe opening a new Thunar with the destination. BTW this repo moved to GitLab: https://gitlab.com/nobodyinperson/thunar-custom-actions  thus closing this issue
