### ISSUE TITLE
Test it on a non-Debian system

### ISSUE THREAD

**Issue by nobodyinperson** [nobodyinperson/thunar-custom-actions#7]
As Thunar runs on basically all distributions, tests not only for Ubuntu/Debian based systems should be performed.

**Comment by jimkp** [comment]
Tested on Korora 25, which is Fedora remix equivalent to Fedora 25. On Thunar 1.6.11.
Needed to install pandoc which is in repos so no issue. There configure, make and make install were run without apparent issue in the verbose output.
~/.local/share/thunar-custom-actions/ exists but no actions appear in Thunar

**Comment by nobodyinperson** [comment]
Okay, you might just have to run `uca-apply update` to merge the provided actions into your configuration. This is not done automatically by `make install`. The debian package does this for you, but as it [says in the README](https://github.com/nobodyinperson/thunar-custom-actions/blob/master/README.md#by-hand) one has to do this oneself on manual installation. 

Otherwise, have you tried the [Troubleshooting in the README](https://github.com/nobodyinperson/thunar-custom-actions/blob/master/README.md#troubleshooting)? That is, close all Thunar windows, run `thunar -q` and then recheck if there are still no actions.

If that does't work, could you please post the output of the following commands:

```bash
# from the repository root
# I assume you did a `./configure --prefix=$HOME/.local PASSWDFILE=`
# remake everything
make -B
# check the `*.xml`-files were made locally
find share/thunar-custom-actions -type f -iname '*.xml'
# install it again
make install
# check if the `*.xml`-files were installed correctly
find $HOME/.local/share/thunar-custom-actions -type f -iname '*.xml'
```

**Comment by jimkp** [comment]
> Okay, you might just have to run uca-apply update to merge the provided actions into your configuration. This is not done automatically by make install

Ah yes, sorry missed that line. Working now, will test more over the next few days. Thanks

**Comment by nobodyinperson** [comment]
Wonderful :-D

**Comment by nobodyinperson** [comment]
This project was moved to [GitLab.com](https://gitlab.com/nobodyinperson/thunar-custom-actions)
